# Generated by Django 2.0.6 on 2019-12-18 03:37

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=600)),
                ('location', models.CharField(max_length=600)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('organization', models.CharField(blank=True, max_length=300, null=True)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('description', models.CharField(max_length=6000)),
                ('event_skill_level', models.CharField(blank=True, choices=[('Newbie', '2 years or less'), ('Intermediate', '3-5 years'), ('Experienced', '5+'), ('No Skill Level', 'No Skill level')], max_length=60, null=True)),
                ('event_age_group', models.CharField(blank=True, choices=[('Youth', '18 and Younger'), ('Young Adult', '18-20'), ('Adult', '21+'), ('All Ages', 'All Ages')], max_length=50, null=True)),
                ('programming_language', models.CharField(blank=True, choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Java', 'Java'), ('HTML', 'HTML'), ('C Programming Language', 'C Programming Language'), ('CSS', 'CSS'), ('Django', 'Django'), ('ReactJS', 'ReactJS'), ('React Native', 'React Native'), ('Swift', 'Swift'), ('SQL', 'SQL'), ('Ruby', 'Ruby'), ('Node.JS', 'Node.JS'), ('UI/UX', 'UI/UX')], max_length=60, null=True)),
                ('event_category', models.CharField(choices=[('Education', 'Education'), ('Social', 'Social'), ('Conference', 'Conference'), ('Special Events', 'Special Events'), ('Youth Programs', 'Youth Programs')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('age_group', models.CharField(choices=[('Youth', '18 and Younger'), ('Young Adult', '18-20'), ('Adult', '21+'), ('All Ages', 'All Ages')], default='Youth', max_length=50)),
                ('skill_level', models.CharField(choices=[('Newbie', '2 years or less'), ('Intermediate', '3-5 years'), ('Experienced', '5+'), ('No Skill Level', 'No Skill level')], default='Newbie', max_length=50)),
                ('tech_experience', models.CharField(choices=[('Education', 'Education'), ('Social', 'Social'), ('Conference', 'Conference'), ('Special Events', 'Special Events'), ('Youth Programs', 'Youth Programs')], default='Education', max_length=50)),
                ('password', models.CharField(max_length=15, unique=True, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
