# Generated by Django 2.0.6 on 2019-12-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechiesApp', '0002_auto_20191217_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skill_level',
            field=models.CharField(choices=[('Newbie', '2 years or less'), ('Intermediate', '3-5 years'), ('Experienced', '5+'), ('No Skill Level', 'No Skill level')], default='Newbie', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_skill_level',
            field=models.CharField(choices=[('Newbie', '2 years or less'), ('Intermediate', '3-5 years'), ('Experienced', '5+'), ('No Skill Level', 'No Skill level')], max_length=60),
        ),
    ]
