# Generated by Django 2.0.6 on 2019-12-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechiesApp', '0003_auto_20191217_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age_group',
            field=models.CharField(choices=[('Youth', '17 and Younger'), ('Young Adult', '18-25'), ('Adult', '26+'), ('All Ages', 'All Ages')], default='Youth', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_age_group',
            field=models.CharField(choices=[('Youth', '17 and Younger'), ('Young Adult', '18-25'), ('Adult', '26+'), ('All Ages', 'All Ages')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_skill_level',
            field=models.CharField(choices=[('Newbie', '2 years or less'), ('Intermediate', '3-5 years'), ('Experienced', '5+'), ('No Skill Level', 'No Skill level')], max_length=60, null=True),
        ),
    ]
