# Generated by Django 2.0.6 on 2019-12-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechiesApp', '0004_auto_20191217_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_skill_level',
            field=models.CharField(blank=True, choices=[('Newbie', '2 years or less'), ('Intermediate', '3-5 years'), ('Experienced', '5+'), ('No Skill Level', 'No Skill level')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='programming_language',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Java', 'Java'), ('HTML', 'HTML'), ('C Programming Language', 'C Programming Language'), ('CSS', 'CSS'), ('Django', 'Django'), ('ReactJS', 'ReactJS'), ('React Native', 'React Native'), ('Swift', 'Swift'), ('SQL', 'SQL'), ('Ruby', 'Ruby'), ('Node.JS', 'Node.JS'), ('UI/UX', 'UI/UX')], max_length=60, null=True),
        ),
    ]
