# Generated by Django 2.0.6 on 2019-12-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechiesApp', '0005_auto_20191217_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_age_group',
            field=models.CharField(blank=True, choices=[('Youth', '17 and Younger'), ('Young Adult', '18-25'), ('Adult', '26+'), ('All Ages', 'All Ages')], max_length=50, null=True),
        ),
    ]
