# Generated by Django 2.0.6 on 2019-12-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechiesApp', '0006_auto_20191217_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
