# Generated by Django 2.0.6 on 2019-12-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechiesApp', '0007_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organization',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
