# Generated by Django 2.0.6 on 2019-12-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechiesApp', '0008_auto_20191217_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age_group',
            field=models.CharField(choices=[('Youth', '18 and Younger'), ('Young Adult', '18-20'), ('Adult', '21+'), ('All Ages', 'All Ages')], default='Youth', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_age_group',
            field=models.CharField(blank=True, choices=[('Youth', '18 and Younger'), ('Young Adult', '18-20'), ('Adult', '21+'), ('All Ages', 'All Ages')], max_length=50, null=True),
        ),
    ]
