# Generated by Django 2.0.6 on 2019-12-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('admin', '0003_auto_20191217_2143'),
        ('TechiesApp', '0009_auto_20191217_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
